[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
winapi = { version = "0.3", features = ["processthreadsapi", "memoryapi", "handleapi", "winnt"] }

[profile.release]
opt-level = "z"

