[package]
name = "stealth_dropper"
version = "0.1.0"
edition = "2021"

# Optional: Add dependencies for more functionality (e.g., for process enumeration)
[dependencies]
rand = "0.8.5"
winapi = { version = "0.3", features = ["winbase", "processthreadsapi", "memoryapi", "winnt"] }

