[package]
name = "rustagenv3"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4"
sysinfo = "0.31.4"
prometheus = "0.13"
rand = "0.8"
reqwest = { version = "0.12.8", features = ["json"] }
winapi = { version = "0.3", features = ["memoryapi", "processthreadsapi", "winnt", "minwindef"] }
