[package]
name = "polymorphicstubcreator"
version = "0.1.0"
edition = "2021"

[dependencies]
goblin = "0.5"
aes = "0.7"
block-modes = "0.8"
flate2 = "1.0"
clap = { version = "3.2", features = ["derive"] }
rand = "0.8"
                                                                                                      
