[package]
name = "c2_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
actix-rt = "2"
futures = "0.3"
tui = "0.19.0"
crossterm = "0.28.1"
reqwest = { version = "0.12.8", features = ["json"] }
