[package]
name = "banker_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"  # For generating random delays
clipboard-win = "4.1"  # For clipboard access on Windows
winapi = { version = "0.3", features = ["winuser", "processthreadsapi", "memoryapi", "minwindef"] }
base64 = "0.22.1"

[profile.release]
opt-level = 3  # Optimize for release builds

